// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTVH2X_fQHSVaY-T--HcpxIopCij8j0o8',
    appId: '1:169554526813:web:00ac189afe3147174283b4',
    messagingSenderId: '169554526813',
    projectId: 'mobileappfcm-88c43',
    authDomain: 'mobileappfcm-88c43.firebaseapp.com',
    storageBucket: 'mobileappfcm-88c43.appspot.com',
    measurementId: 'G-HVNGJMZVXR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSsMx8rAIxDtwrTZ304-mpxAYRbwM3X1c',
    appId: '1:169554526813:android:7935fe5f2f0d69ce4283b4',
    messagingSenderId: '169554526813',
    projectId: 'mobileappfcm-88c43',
    storageBucket: 'mobileappfcm-88c43.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2FQ2TO2QatnEqCK4hiceIBbKFRn22EyU',
    appId: '1:169554526813:ios:d1e45036de07b8354283b4',
    messagingSenderId: '169554526813',
    projectId: 'mobileappfcm-88c43',
    storageBucket: 'mobileappfcm-88c43.appspot.com',
    iosClientId: '169554526813-j3ls9ph82mfa2q14ojmjd2cmq8mhnjnp.apps.googleusercontent.com',
    iosBundleId: 'com.school.eSchoolLearning',
  );
}
